#!/usr/bin/env python3
"""Build gate for a Carbon Arc client deliverable.

`verify_report.py` checks the WORDS. This checks the FILE. The two failures it
catches are the ones ca-core SKILL.md calls silent: a single-file Artifact that
still links ./assets/ renders in system sans with no error anywhere, and a chart
carrying a pre-rebrand color looks deliberate.

Checks
  fonts_inlined      every @font-face src is a data: URI; the three open-license faces
                     (Hanken Grotesk, DM Mono, Doto) are present; no licensed brand face
                     (26A1 Marund, MD Thermochrome) is embedded
  no_external_refs   no <script src>, <link href>, <img src> or url() pointing off-document
  no_legacy_palette  every hex in the document is in the v2 rebrand palette
  size_sane          the file is large enough to actually contain its fonts
  chart_sources      every chart card (an element with id="ch-…") carries a ■/▲/◆ source
                     chip, and every ■ chip starts with a Carbon Arc dataset name from
                     datasets.txt, not a nickname such as "Card panel"
  ai_disclaimer      the AI disclaimer appears word for word, after the last "Sources & method"
                     heading (carbon-arc-report-v2/carbon-arc-report.md, Appendix)

Usage: verify_build.py <report.html> [--allow RRGGBB,RRGGBB] [--dataset="Name"] [--quiet]
Exit 1 if anything fails.
"""
import sys, re, pathlib, html as htmllib

# Ends Sources & method in every deliverable. Change it here and in carbon-arc-report.md together.
AI_DISCLAIMER = "Generated by AI via Carbon Arc Skills. Not reviewed by Carbon Arc."

# The report's faces are open-license (SIL OFL): carbon-arc-report-v2/assets/fonts.css.
EXPECTED_FACES = ("Hanken Grotesk", "DM Mono", "Doto")
# Licensed brand binaries that must never ship in a client report.
LICENSED_FACES = re.compile(r"marund|thermochrome", re.I)

# The 2026 rebrand system, from skills/carbon-arc-report-v2/carbon-arc-report.md.
# A hex outside this set is either a pre-rebrand leftover or an invention; both ship
# as a deliberate-looking brand error. Extend this list only when that file changes.
#
# UNRESOLVED, 2026-09-21. Three grays below are marked DISPUTED. The Red Antler brand
# reference (carbon-arc-brand-refresh, correction dated 08/13/2026) states that #CACACA,
# #B3B3B3 and #545454 "do not appear anywhere in the actual guidelines" and that the real
# gray scale is six values: #FFFFFF, #EDEDED, #7D7D7D, #323232, #151515, #000000. The
# report-v2 system is built on all three. They are allowed here so this gate reflects what
# the package currently ships rather than a guess, and they are labelled so the conflict is
# visible. Resolving it is a design decision, not a lint fix: it changes body text, every
# hairline and the nav numerals in every deliverable.
PALETTE = {
    "151515": "Gray 800, canvas",
    "323232": "Gray 700, cards",
    "545454": "Border / Strong, hairline. DISPUTED, see note above",
    "7d7d7d": "Gray 500, metadata",
    "cacaca": "Gray 300, body text. DISPUTED, see note above",
    "b3b3b3": "nav numerals in template.html. DISPUTED, and not in carbon-arc-report.md either",
    "ededed": "Gray 200, in the brand guidelines and currently unused by report-v2",
    "ffffff": "Text / Inverse",
    "000000": "pure black, permitted in masks and shadows-free SVG defs",
    "ff7125": "Orange 500, the single accent",
    "ff8c4d": "Orange 500 hover",
    "d1540f": "Orange 500 press",
    "662d0f": "Orange 800, highlighted row and event marker",
    "5585ff": "Periwinkle 500, series 2",
    "68d133": "Emerald 500, series 3 and positive",
    "dfda25": "Yellow 500, series 4, loss and caution",
    "ffc6a8": "Orange ramp tint",
    "ff8d51": "Orange ramp tint",
    "cc5a1e": "Orange ramp shade",
    "994416": "Orange ramp shade",
}


HERE = pathlib.Path(__file__).parent
CHIP = re.compile(r"<span[^>]*border-radius:\s*100px[^>]*>\s*([■▲◆][^<]*)</span>", re.I)
# 24px is a standard chart card; 32px is the Brief's headline hero card (carbon-arc-report.md §7).
CARD = re.compile(r"background:\s*#323232[^>]*border-radius:\s*(24|32)px|border-radius:\s*(24|32)px[^>]*background:\s*#323232", re.I)


def _norm(t):
    return re.sub(r"[\s,–—-]+", " ", t).strip().lower()


def load_datasets(extra):
    f = HERE / "datasets.txt"
    names = [l.strip() for l in f.read_text().splitlines() if l.strip() and not l.startswith("#")] if f.exists() else []
    return [_norm(n) for n in names + list(extra)]


def chart_sources(doc, datasets):
    """Return (fails, note). Cards and chips are static markup in report-v2; charts mount later."""
    fails = []
    starts = [m.start() for m in CARD.finditer(doc)]
    chips = [(m.start(), m.group(1).strip()) for m in CHIP.finditer(doc)]
    mounts = [(m.start(), m.group(1)) for m in re.finditer(r'id="(ch-[^"]+)"', doc)]
    missing = []
    for pos, mid in mounts:
        card = max([s for s in starts if s < pos], default=None)
        if card is None or not any(card < c < pos for c, _ in chips):
            missing.append(mid)
    if missing:
        fails.append(("chart_sources",
                      f"{len(missing)} chart(s) with no source chip on the card: {', '.join(missing[:6])}. "
                      "Every chart names its dataset on the card itself."))
    bad = sorted({t for _, t in chips if t.startswith("■")
                  and not any(_norm(t[1:]).startswith(d) for d in datasets)})
    if bad:
        fails.append(("chart_sources",
                      f"{len(bad)} ■ chip(s) do not start with a Carbon Arc dataset name: "
                      + "; ".join(bad[:6]) + ". Use the name the Sources table lists "
                      "(e.g. \"■ Credit Card – US Complete Panel · …\"), or pass --dataset if it is new."))
    note = f"chart_sources     {len(mounts)} charts, {len(chips)} chips, all named" if not fails else None
    return fails, note


def checks(path, allow, datasets=()):
    doc = pathlib.Path(path).read_text(encoding="utf-8")
    fails, notes = [], []

    # --- fonts_inlined -----------------------------------------------------
    n_data = len(re.findall(r"data:font/woff2;base64", doc))
    face_srcs = re.findall(r"@font-face\s*\{[^}]*?src:\s*url\((['\"]?)([^)'\"]+)\1\)", doc, re.S | re.I)
    linked = [u for _, u in face_srcs if not u.startswith("data:")]
    if linked:
        fails.append(("fonts_inlined",
                      f"{len(linked)} @font-face src still links a file: {', '.join(sorted(set(linked))[:4])}. "
                      "The page will render in system sans with no error."))
    else:
        families = re.findall(r"@font-face\s*\{[^}]*?font-family:\s*['\"]([^'\"]+)['\"]", doc, re.S | re.I)
        licensed = sorted({f for f in families if LICENSED_FACES.search(f)})
        missing = [f for f in EXPECTED_FACES if f not in families]
        if licensed:
            fails.append(("fonts_inlined",
                          f"licensed brand face embedded: {', '.join(licensed)}. It may not be handed to a "
                          "client; use Hanken Grotesk / DM Mono / Doto (carbon-arc-report-v2/assets/fonts.css)."))
        elif missing or n_data < len(EXPECTED_FACES):
            fails.append(("fonts_inlined",
                          f"{n_data} base64 font payloads; missing {', '.join(missing) or 'a payload'}. "
                          "A missing face falls back silently."))
        else:
            notes.append(f"fonts_inlined     {n_data} faces embedded ({', '.join(EXPECTED_FACES)})")

    # --- no_external_refs --------------------------------------------------
    ext = []
    for m in re.finditer(r"""<script[^>]+src=(['"])(?!data:)([^'"]+)\1""", doc, re.I):
        ext.append("<script src=" + m.group(2))
    for m in re.finditer(r"""<link[^>]+href=(['"])(?!data:)([^'"]+)\1""", doc, re.I):
        ext.append("<link href=" + m.group(2))
    for m in re.finditer(r"""<img[^>]+src=(['"])(?!data:)([^'"]+)\1""", doc, re.I):
        ext.append("<img src=" + m.group(2))
    for m in re.finditer(r"""url\((['"]?)(?!data:)([^)'"]+\.(?:woff2?|svg|png|jpe?g|css))\1\)""", doc, re.I):
        ext.append("url(" + m.group(2) + ")")
    # Google Fonts is the one permitted remote stylesheet host; nothing else is.
    ext = [e for e in ext if "fonts.googleapis.com" not in e and "fonts.gstatic.com" not in e]
    if ext:
        fails.append(("no_external_refs",
                      f"{len(ext)} reference(s) resolve off-document: " + "; ".join(sorted(set(ext))[:6])))
    else:
        notes.append("no_external_refs  self-contained")

    # --- no_legacy_palette -------------------------------------------------
    body = re.sub(r"data:[a-z/+-]+;base64,[A-Za-z0-9+/=]+", " ", doc)
    found = {}
    for m in re.finditer(r"#([0-9A-Fa-f]{6})\b", body):
        h = m.group(1).lower()
        found.setdefault(h, 0)
        found[h] += 1
    for m in re.finditer(r"#([0-9A-Fa-f]{3})\b", body):
        h = "".join(c * 2 for c in m.group(1).lower())
        found.setdefault(h, 0)
        found[h] += 1
    unknown = {h: c for h, c in found.items() if h not in PALETTE and h not in allow}
    if unknown:
        listing = ", ".join(f"#{h} x{c}" for h, c in sorted(unknown.items(), key=lambda kv: -kv[1])[:8])
        fails.append(("no_legacy_palette",
                      f"{len(unknown)} hex value(s) are not in the v2 palette: {listing}. "
                      "Map each to the rebrand system, or pass --allow if it is a deliberate one-off."))
    else:
        notes.append(f"no_legacy_palette {len(found)} distinct hexes, all in palette")

    # --- size_sane ---------------------------------------------------------
    kb = len(doc.encode()) / 1024
    if kb < 75:
        fails.append(("size_sane",
                      f"{kb:.0f}KB. The three faces alone embed to about 65KB, so a full build lands "
                      "well above 75KB; this one is probably missing its fonts."))
    else:
        notes.append(f"size_sane         {kb:.0f}KB")

    # --- chart_sources -----------------------------------------------------
    f2, note = chart_sources(doc, datasets)
    fails += f2
    if note:
        notes.append(note)

    # --- ai_disclaimer -----------------------------------------------------
    # Rendered text, not markup, so a tag or an entity inside the sentence cannot hide it.
    # The report's Method tab may be filled from data.js, so script text is searched too.
    text = re.sub(r"<[^>]+>", " ", re.sub(r"data:[a-z/+-]+;base64,[A-Za-z0-9+/=]+", " ", doc))
    text = re.sub(r"\s+", " ", htmllib.unescape(text))
    at = text.rfind(AI_DISCLAIMER)
    heading = text.lower().rfind("sources & method")
    if at < 0:
        fails.append(("ai_disclaimer",
                      f'missing. Sources & method must end with, word for word: "{AI_DISCLAIMER}"'))
    elif heading < 0 or at < heading:
        fails.append(("ai_disclaimer",
                      "present, but not inside Sources & method. It goes at the end of that section."))
    else:
        notes.append("ai_disclaimer     present in Sources & method")

    return fails, notes


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    if not args:
        print("usage: verify_build.py <report.html> [--allow RRGGBB,RRGGBB] [--dataset=\"Name\"] [--quiet]")
        return 2
    allow = set()
    for a in argv:
        if a.startswith("--allow"):
            allow = {h.strip().lstrip("#").lower() for h in a.split("=", 1)[-1].split(",") if h.strip()}
    extra = [a.split("=", 1)[1].strip('"') for a in argv if a.startswith("--dataset=")]
    try:
        fails, notes = checks(args[0], allow, load_datasets(extra))
    except FileNotFoundError:
        print(f"ERROR  no such file: {args[0]}")
        return 2
    if "--quiet" not in argv:
        for n in notes:
            print("OK     " + n)
    for name, why in fails:
        print(f"FAIL   {name:17} {why}")
    print(f"\n{len(fails)} failure(s), {len(notes)} check(s) passed")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
